global:
    checkNewVersion: false
    sendAnonymousUsage: false

entryPoints:
    web:
        address: ':80'
    websecure:
        address: ':443'
    traefik:
        address: ':8080'

providers:
    consulCatalog:
        exposedByDefault: false
        endpoint:
            address: '{{ env "CONSUL_HTTP_ADDR" }}'
            token: '{{ env "CONSUL_HTTP_TOKEN" }}'

certificatesResolvers:
    letsencrypt:
        acme:
            email: '{{ with env "ACME_EMAIL" }}{{ . }}{{ else }}admin@local.dev{{ end }}'
            storage: '/tmp/acme.json'
            keyType: 'EC256'
            httpChallenge:
                entryPoint: 'web'

api:
    dashboard: true
    insecure: true

ping: {}

log:
    level: 'INFO'

accessLog: { }

metrics:
    prometheus:
        addEntryPointsLabels: true
        addServicesLabels: true
